### ISSUE TITLE
Feature request: get index as arg

### ISSUE THREAD

**Issue by karlTGA** [normanrz/limited-map#1]
I want to track the process of the limited map and so i need the index in every function. 
It would be perfect if I could pass this as an optional argument. Like so:

`limitedMap(calls, (setup, index) => uploadDataDirectly(setup,index), 10)`

**Comment by normanrz** [comment]
Yep. It already does that. It has the same API as regular map function:
https://github.com/normanrz/limited-map/blob/master/index.js#L20
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/map
